# This pre-commit config file describes what repositories and hooks are installed.
  # See https://pre-commit.com for more information.
    # See https://pre-commit.com/hooks.html for more hooks.
      # Terraform pre-commit hooks referenced here:  https://github.com/antonbabenko/pre-commit-terraform

# To get the latest versions on all repositories run 'pre-commit autoupdate' in terminal before or after 'pre-commit install'.

repos:
    - repo: meta
      hooks:
          - id: check-hooks-apply

    # Hadolint - This Repo lint Dockerfiles using hadolint without needing docker or system installation
    - repo: https://github.com/AleksaC/hadolint-py
      rev: v2.10.0
      hooks:
          - id: hadolint
            # For info on DL#### codes, see https://github.com/hadolint/hadolint/wiki/DL3033 -> replace < DL3033 > with your code to see more information.
            args: [--ignore, DL3033, --ignore, DL3018]

    # Shell Check
    - repo: https://github.com/koalaman/shellcheck-precommit
      rev: v0.8.0
      hooks:
          - id: shellcheck
            # args: [--exclude, SC2012, --exclude, SC2207] # disable checks here or directly in the .sh file - for ex. see additional_userdata.sh
    # TFlint, Terraform Format, Terraform Validate, Checkov
    - repo: https://github.com/antonbabenko/pre-commit-terraform
      rev: v1.77.0
      hooks:
          # Terraform Format
          - id: terraform_fmt
            args:
              # - --args=-check
              - --args=-recursive
          # Terraform Validate
          - id: terraform_validate
          # TFlint
          - id: terraform_tflint
            args:
              - --args=--init
              - --args=--module
              - --args=--var-file="terraform.tfvars"
              - --args=--disable-rule=terraform_deprecated_index
              - --args=--disable-rule=terraform_unused_declarations
              - --args=--disable-rule=terraform_typed_variables
              - --args=--disable-rule=terraform_deprecated_interpolation
          # Checkov
          - id: terraform_checkov
            args:
              - --args=--quiet # quiet means that only fails are presented in the cli
              - --args=--download-external-modules terraform
              # AWS CHECKS to IGNORE - see check information at https://www.checkov.io/5.Policy%20Index/terraform.html
              - --args=--skip-check CKV_AWS_3
              - --args=--skip-check CKV_AWS_8
              - --args=--skip-check CKV_AWS_42
              - --args=--skip-check CKV_AWS_79
              - --args=--skip-check CKV_AWS_111
              - --args=--skip-check CKV_AWS_126
              - --args=--skip-check CKV_AWS_130
              - --args=--skip-check CKV_AWS_135
              - --args=--skip-check CKV_AWS_184
              - --args=--skip-check CKV_AWS_189
              - --args=--skip-check CKV2_AWS_2
              - --args=--skip-check CKV2_AWS_5
              - --args=--skip-check CKV2_AWS_11
              - --args=--skip-check CKV2_AWS_12
              - --args=--skip-check CKV2_AWS_41
              - --args=--skip-check CKV2_AWS_184
              # DOCKER CHECKS to IGNORE - see check information at https://www.checkov.io/5.Policy%20Index/dockerfile.html
              - --args=--skip-check CKV_DOCKER_2
              # - --args=--skip-check CKV_DOCKER_3

    # Common Pre-Commit Checks
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.4.0
      hooks:
          # Security
          - id: detect-aws-credentials # detects *your* aws credentials from the aws cli credentials file.
            args: [--allow-missing-credentials]
          - id: detect-private-key # detects the presence of private keys.

          # Git style
          - id: check-merge-conflict # checks for files that contain merge conflict strings.
          - id: check-added-large-files # prevents giant files from being committed.

          # Common Errors
          - id: trailing-whitespace # trims trailing whitespace.
          - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline.
          - id: check-yaml # checks yaml files for parseable syntax.
