---
- name: Install Grafana
  hosts: main
  become: yes
  
  tasks:
  - name: Download Apt Key
    ansible.builtin.apt_key:
      url: https://packages.grafana.com/gpg.key
      state: present
  - name: Add Grafana Repo to sources.list
    ansible.builtin.apt_repository:
      repo: deb https://packages.grafana.com/oss/deb stable main
      filename: grafana
      state: present
  - name: Update Apt Cache and Install Grafana
    ansible.builtin.apt:
      name: grafana
      update_cache: yes
  - name: Inseure Grafana is Enabled and Started
    ansible.builtin.systemd:
      name: grafana-server
      enabled: yes
      state: started