name: Hadolint Linting
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  hadolint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - name: Hadolint Action
        uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile