# For more information on the Hadolint Github Action, see - https://github.com/marketplace/actions/hadolint-action
# For more information on Hadolint, see - https://github.com/hadolint/hadolint#how-to-use
# For more information on the Hadolint Wiki, see - https://github.com/hadolint/hadolint/wiki/<type rule here>

name: Hadolint Action - Linting Dockerfiles
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  Hadolint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - uses: hadolint/hadolint-action@v3.0.0
        with:
          dockerfile: Dockerfile