# For more information on the ShellCheck Github Action, see - https://github.com/ludeeus/action-shellcheck
# For more information on the ShellCheck Wiki Sitemap, see - https://www.shellcheck.net/wiki/<type rule here>

name: Shellcheck Action - Linting Shell Scripts
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ShellCheck:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
      - uses: actions/checkout@v3
      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master