# For more information on the TFLint Github Action, see - https://github.com/terraform-linters/setup-tflint
# For more information on TFLint, see - https://github.com/terraform-linters/tflint
# For more information on the TFLint Terraform Ruleset, see - https://github.com/terraform-linters/tflint-ruleset-terraform
# For more information on the TFLint AWS Ruleset, see - https://github.com/terraform-linters/tflint-ruleset-aws

name: TFLint Action - Linting Terraform & AWS
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  TFLint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v2
      name: Checkout Source Code

    - uses: actions/cache@v2
      name: Cache Plugin Dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v2
      name: Setup TFLint
      with:
        github_token: ${{ secrets.MY_CUSTOM_GITHUB_TOKEN }}
        tflint_version: latest

    - name: Show Version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint